services:
  server:
    container_name: "nest-api"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    build:
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - ./generated:/usr/src/app/generated
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: npm run start:dev
    networks:
      postgres-db-network:


  postgres:
    image: postgres:15
    container_name: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      postgres-db-network:

  pgadmin:
    image: dpage/pgadmin4
    container_name: "postgres-admin"
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "16543:80"
    networks:
      postgres-db-network:

volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  dev_net:
  postgres-db-network:
    driver: bridge
